name: Update UDI Value

on:
  schedule:
    - cron: '0 0 * * *' # Esto se ejecutará diariamente a la medianoche
  workflow_dispatch:

jobs:
  update-udi:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch UDI Value
        id: fetch_udi
        env:
          BANXICO_API_TOKEN: ${{ secrets.BANXICO_API_TOKEN }}
        run: |
          response=$(curl -s -H "Bmx-Token: $BANXICO_API_TOKEN" "https://www.banxico.org.mx/SieAPIRest/service/v1/series/SERIES_ID/datos/oport")
          udi_value=$(echo $response | jq -r '.bmx.series[0].datos[0].dato')
          udi_date=$(echo $response | jq -r '.bmx.series[0].datos[0].fecha')
          echo "::set-output name=udi_value::$udi_value"
          echo "::set-output name=udi_date::$udi_date"

      - name: Update index.html
        run: |
          udi_value=${{ steps.fetch_udi.outputs.udi_value }}
          udi_date=${{ steps.fetch_udi.outputs.udi_date }}
          sed -i "s/<h1>Valor de Referencia de 1 UDI.*/Valor de Referencia de 1 UDI al día de $UDI_DATE<\/h1>/" index.html
          sed -i "s/<p id="udi-value">.*/1 UDI = $UDI_VALUE MXN/" index.html

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update UDI value"
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git HEAD:main
